version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://treechat:treechat123@db:5432/treechat_demo
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: python app.py

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=treechat_demo
      - POSTGRES_USER=treechat
      - POSTGRES_PASSWORD=treechat123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schemas:/docker-entrypoint-initdb.d

volumes:
  postgres_data: